name: Deploy to Ubuntu Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Deploy app
        run: |
          cd /home/phamezan/BookmarkManager
          git fetch origin main
          git reset --hard origin/main
          docker compose up -d --build --force-recreate
          docker image prune -f
